### ISSUE TITLE
Request permission for camera access crasshes on first attemp

### ISSUE THREAD

**Issue by javier7ar** [cientopolis/samplers#60]
Tested on a phone with android 6.1

**Comment by Lilauth** [comment]
Explanation about when asking for permissions and how to do it in the right way/moment
https://www.youtube.com/watch?v=iZqDdvhTZj0

**Comment by Lilauth** [comment]
It also happens in Android 6 (API 23). It is related on how Android manage and save state on nested fragments. It does not happens in Android 7

**Comment by Lilauth** [comment]
07-16 19:51:52.923 3469-3469/org.cientopolis.sampleapplication E/TakeSampleActivity:  onSaveInstanceState
07-16 19:51:52.929 3469-3469/org.cientopolis.sampleapplication D/AndroidRuntime: Shutting down VM
07-16 19:51:52.929 3469-3469/org.cientopolis.sampleapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: org.cientopolis.sampleapplication, PID: 3469
                                                                                 java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.cientopolis.samplers.ui.take_sample.PhotoFragment)
	at android.os.Parcel.writeSerializable(Parcel.java:1447)
	at android.os.Parcel.writeValue(Parcel.java:1395)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
	at android.os.Bundle.writeToParcel(Bundle.java:1079)
	at android.os.Parcel.writeBundle(Parcel.java:690)
	at android.app.FragmentState.writeToParcel(Fragment.java:140)
	at android.os.Parcel.writeTypedArray(Parcel.java:1233)
	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:380)
	at android.os.Parcel.writeParcelable(Parcel.java:1416)
	at android.os.Parcel.writeValue(Parcel.java:1322)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
	at android.os.Bundle.writeToParcel(Bundle.java:1079)
	at android.os.Parcel.writeBundle(Parcel.java:690)
	at android.app.FragmentState.writeToParcel(Fragment.java:141)
	at android.os.Parcel.writeTypedArray(Parcel.java:1233)
	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:380)
	at android.os.Parcel.writeParcelable(Parcel.java:1416)
	at android.os.Parcel.writeValue(Parcel.java:1322)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
	at android.os.Bundle.writeToParcel(Bundle.java:1079)
	at android.os.Parcel.writeBundle(Parcel.java:690)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3152)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	Caused by: java.io.NotSerializableException: org.cientopolis.samplers.ui.take_sample.Camera2Fragment
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at android.os.Parcel.writeSerializable(Parcel.java:1442)
	at android.os.Parcel.writeValue(Parcel.java:1395) 
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:665) 
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
	at android.os.Bundle.writeToParcel(Bundle.java:1079) 
	at android.os.Parcel.writeBundle(Parcel.java:690) 
	at android.app.FragmentState.writeToParcel(Fragment.java:140) 
	at android.os.Parcel.writeTypedArray(Parcel.java:1233) 
	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:380) 
	at android.os.Parcel.writeParcelable(Parcel.java:1416) 
	at android.os.Parcel.writeValue(Parcel.java:1322) 
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:665) 
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
	at android.os.Bundle.writeToParcel(Bundle.java:1079) 
	at android.os.Parcel.writeBundle(Parcel.java:690) 
	at android.app.FragmentState.writeToParcel(Fragment.java:141) 
	at android.os.Parcel.writeTypedArray(Parcel.java:1233) 
	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:380) 
	at android.os.Parcel.writeParcelable(Parcel.java:1416) 
	at android.os.Parcel.writeValue(Parcel.java:1322) 
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:665) 
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
	at android.os.Bundle.writeToParcel(Bundle.java:1079) 
	at android.os.Parcel.writeBundle(Parcel.java:690) 
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3152) 
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417) 
	at android.os.Handler.handleCallback(Handler.java:739) 
	at android.os.Handler.dispatchMessage(Handler.java:95) 
	at android.os.Looper.loop(Looper.java:148) 
	at android.app.ActivityThread.main(ActivityThread.java:5417) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
